spring:
  application:
    name: Eureka

server:
  port: 8761

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
